substitutions:
  name: esphome_c31
esphome:
  name: $name
  platformio_options:
    board_build.f_flash: 40000000L
    board_build.flash_mode: dio
    board_build.flash_size: 4MB
    board_build.variant: esp32c3

esp32:
  #board: lolin_c3_mini
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework:
    type: arduino
    version: 2.0.5
    platform_version: 5.2.0

# Enable Home Assistant API
api:

bluetooth_proxy:
  active: true

ota:

logger:
  baud_rate: 0

web_server:
 port: 80
external_components:
  - source: github://dentra/esphome-components
backup:
  auth:
    username: !secret web_username
    password: !secret web_password
  force_update: false

wifi:
  ssid: !secret wifi_iot_ssid
  password: !secret wifi_iot_password
  use_address: 192.168.8.166
  output_power: "8.5"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: $name
    password: $name

captive_portal:

light:
  - platform: status_led
    name: "Switch state"
    pin: 7

i2c:
  sda: 8
  scl: 10
  frequency: 50kHz

uart:
  tx_pin: 21
  rx_pin: 20
  baud_rate: 9600

spi:
  clk_pin: 2  # D5
  mosi_pin: 4  # D7
  miso_pin: 3  # D6

font:
  - file: "font/Sono/static/Sono/Sono-Light.ttf"
    id: labels
    size: 15
    glyphs: "!\"%()+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz<µ/³"
  - file: "font/Open_Sans/static/OpenSans_Condensed/OpenSans_Condensed-Bold.ttf"
    id: big_chars
    size: 60
    glyphs: "!\"%()+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz<µ/³"
  - file: "font/Open_Sans/static/OpenSans_Condensed/OpenSans_Condensed-Bold.ttf"
    id: big_labels
    size: 30
    glyphs: "!\"%()+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz<µ/³"
  - file: "font/Sono/static/Sono/Sono-Light.ttf"
    id: small_chars
    size: 14
    glyphs: "!\"%()+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz<µ/³"
  - file: "font/slkscr.ttf"
    id: labels_small
    size: 8
    glyphs: "!\"%()+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz<µ"


display:
  - platform: waveshare_epaper
    cs_pin: 1  # D0
    dc_pin: 5  # D8
    # busy_pin: 7 # D3 TS_CS
    # reset_pin: D5
    full_update_every: 300
    update_interval: 5s
    model: 1.54in
    # full_update_every: 30
    rotation: 180
    pages:
      - id: page1
        lambda: |-
          it.print(120, 0, id(labels_small), TextAlign::TOP_RIGHT, "Temperature");
          it.printf(100, 68, id(big_chars), TextAlign::BOTTOM_RIGHT, "%.1f", id(temp).state);
          it.print(100, 58, id(big_labels), TextAlign::BOTTOM_LEFT, "°C");

          it.print(120, 70, id(labels_small), TextAlign::TOP_RIGHT, "Humidity");
          it.printf(100,148, id(big_chars), TextAlign::BOTTOM_RIGHT, "%.1f", id(humidity).state);
          it.print(100, 138, id(big_labels), TextAlign::BOTTOM_LEFT, "%");

          it.print(130,  0 * (10.0 + 18)      + 0 * 5, id(labels_small), "- Light");
          it.printf(130, 0 * (10.0 + 18) + 9 + 0 * 5, id(small_chars), "%.1f lux", id(illuminance).state);
          it.print(130,  1 * (10.0 + 18)      + 1 * 5, id(labels_small), "- TVOC");
          it.printf(130, 1 * (10.0 + 18) + 9 + 1 * 5, id(small_chars), "%.1f ppb", id(tvoc).state);
          it.print(130,  2 * (10.0 + 18)      + 1 * 5, id(labels_small), "- eCO2");
          it.printf(130, 2 * (10.0 + 18) + 9 + 1 * 5, id(small_chars), "%.1f ppm", id(eco2).state);

          it.print(130,  3 * (10.0 + 18)      + 2 * 5, id(labels_small), "- PM<2.5um");
          it.printf(130, 3 * (10.0 + 18) + 9 + 2 * 5, id(small_chars), "%.1fµg/m³", id(pm_2_5).state);
          it.print(130,  4 * (10.0 + 18)      + 2 * 5, id(labels_small), "- PM<10.0um");
          it.printf(130, 4 * (10.0 + 18) + 9 + 2 * 5, id(small_chars), "%.1fµg/m³", id(pm_10_0).state);

          it.printf(0, 200, id(labels_small), TextAlign::BOTTOM_LEFT, "Uptime %s", id(uptime_human).state.c_str() );
          it.printf(200, 200, id(labels_small), TextAlign::BOTTOM_RIGHT, "%.1fdBm", id(wifi_rssi).state);

time:
  - platform: sntp
    id: sntp_time
sensor:
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 15s
    filters:
      - sliding_window_moving_average:
          window_size: 4
          send_every: 2
    id: wifi_rssi

  - platform: sds011
    pm_2_5:
      name: "Particulate Matter <2.5µm Concentration"
      id: pm_2_5
      filters:
      - sliding_window_moving_average:
          window_size: 5
          send_every: 1
    pm_10_0:
      name: "Particulate Matter <10.0µm Concentration"
      id: pm_10_0
      filters:
      - sliding_window_moving_average:
          window_size: 5
          send_every: 1
    update_interval: 5min

  - platform: sht3xd
    temperature:
      id: temp
      name: "Temperature"
      filters:
      - sliding_window_moving_average:
          window_size: 15
          send_every: 5
    humidity:
      id: humidity
      name: "Humidity"
      filters:
      - sliding_window_moving_average:
          window_size: 15
          send_every: 5
    address: 0x45
    update_interval: 1s

  - platform: bh1750
    id: illuminance
    name: "Illuminance"
    address: 0x23
    update_interval: 5s
  - platform: uptime
    name: Uptime Sensor
    id: uptime_sensor
    update_interval: 10s
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: uptime_human
            state: !lambda |-
              int seconds = round(id(uptime_sensor).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? to_string(days) + "d " : "") +
                (hours ? to_string(hours) + "h " : "") +
                (minutes ? to_string(minutes) + "m " : "") +
                (to_string(seconds) + "s")
              ).c_str();
  - platform: sgp30
    eco2:
      name: "eCO2"
      accuracy_decimals: 1
      id: eco2
      filters:
        - sliding_window_moving_average:
            window_size: 60
            send_every: 30
    tvoc:
      name: "TVOC"
      accuracy_decimals: 1
      id: tvoc
      filters:
        - sliding_window_moving_average:
            window_size: 60
            send_every: 30
    # 19/11/2021 0x9463, TVOC baseline: 0x93BE
    # 20/11/2021 0x9301, TVOC baseline: 0x94BC
    # 19/01/2022 eCO2 0x8FBD, TVOC baseline: 0x94EE
    # 29/08/2022 eCO2 0x8DE9, TVOC baseline: 0x9207
    baseline:
      eco2_baseline: 0x8DE9
      tvoc_baseline: 0x9207
    store_baseline: true
    address: 0x58
    update_interval: 1s
    compensation:
      temperature_source: temp
      humidity_source: humidity

text_sensor:
  - platform: template
    name: Uptime Human Readable
    id: uptime_human
    icon: mdi:clock-start
