---
.x-humidity-number-template: &humidity_number_template
    platform: template
    # Optional variables:
    icon: "mdi:cloud-percent"
    unit_of_measurement: "%"
    optimistic: true
    min_value: 0
    max_value: 100
    step: 1
    restore_value: true
    initial_value: 50

number:
  - <<: *humidity_number_template
    name: Target Humidity 1
    id: target_humidity_1
  - <<: *humidity_number_template
    name: Target Humidity 2
    id: target_humidity_2
  - <<: *humidity_number_template
    name: Target Humidity 3
    id: target_humidity_3
