---
# Example configuration entry
number:
  - id: number_of_cycles
    platform: template
    name: "Consecutive cycles"
    optimistic: true
    min_value: 0
    max_value: 10
    step: 1
    initial_value: 3