substitutions:
  name: clouddrip
  ip: clouddrip-27be74.local
  filename: cloud_dripper/esp_cloud_dripper_window_1.yaml


packages:
  pinout: !include _pinout.yaml
  humidity_sensor1: !include 
    file: _humidity_sensor.yaml
    vars: 
      id: 1
      pin: ${gpio_sense_1}
  humidity_sensor2: !include
    file: _humidity_sensor.yaml
    vars:
      id: 2
      pin: ${gpio_sense_2}
  humidity_sensor3: !include
    file: _humidity_sensor.yaml
    vars:
      id: 3
      pin: ${gpio_sense_3}
  leds: !include _leds.yaml
  sprinklers: !include _sprinklers.yaml
  system: !include _system_base.yaml
  pumps: !include _pumps_switches.yaml
  additiona_sensors: !include _additional_sensors.yaml
  settings: !include _configurable_settings.yaml

font:
  - file: "../font/nerd_fonts/ProggyCleanCENerdFontMono-Regular.ttf"
    id: gliphs
    size: 34
    glyphs: "󰓾󰧱"
  - file: "../font/Sono/static/Sono/Sono-Regular.ttf"
    id: labels
    glyphs: "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890- .,:&|/°%"
    size: 14
  - file: "../font/Sono/static/Sono/Sono-Regular.ttf"
    id: font_standard
    glyphs: "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890- .,:&|/°%"
    size: 12
  - file: "../font/slkscr.ttf"
    id: font_small
    glyphs: "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890- .,:&|/°%"
    size: 8
  - file: "../font/nerd_fonts/ProggyCleanCENerdFontMono-Regular.ttf"
    id: small_gliphs
    size: 18
    glyphs: "󰖎󱡕󰔄󰟤󱫡󱩅󰖩󰀂"
display:
  - platform: ssd1306_i2c
    rotation: 180
    model: "SSD1306 128x64"
    lambda: |-
      it.print(0, 8, id(gliphs), TextAlign::CENTER_LEFT, u8"");
      it.print(18, 0, id(labels), u8"CloudDripper");

      it.print(0, 18 + 5, id(gliphs), TextAlign::CENTER_LEFT, u8"");

      it.graph(15, 18, id(temperature_graph_1));
      it.graph(15 + 36, 18, id(temperature_graph_2));
      it.graph(15 + 36*2, 18, id(temperature_graph_3));

      it.printf(15, 40, id(font_standard), u8"%.0f%%", TextAlign::RIGHT, id(humidity_1).state); 
      it.printf(15+36, 40, id(font_standard), u8"%.0f%%", TextAlign::RIGHT, id(humidity_2).state); 
      it.printf(15+36*2, 40, id(font_standard), u8"%.0f%%", TextAlign::RIGHT, id(humidity_3).state);


      it.print (100, 64 - 5, id(small_gliphs), TextAlign::CENTER_RIGHT, u8"󰖩");
      it.printf(100, 64, id(font_small), TextAlign::BOTTOM_LEFT, "%.0f", id(wifi_rssi).state);
      it.print (13, 64 - 5, id(small_gliphs), TextAlign::CENTER_RIGHT, u8"󰀂");
      it.printf(16, 64 , id(font_small), TextAlign::BOTTOM_LEFT, "%s", id(wifi_ip).state.c_str() );

graph:
  - id: temperature_graph_1
    duration: 1h
    y_grid: 50
    width: 35
    height: 20
    max_range: 100
    min_range: 1
    sensor: humidity_1
  - id: temperature_graph_2
    duration: 1h
    y_grid: 50
    width: 35
    height: 20
    max_range: 100
    min_range: 1
    sensor: humidity_2
  - id: temperature_graph_3
    duration: 1h
    y_grid: 50
    width: 35
    height: 20
    max_range: 100
    min_range: 1
    sensor: humidity_3
