substitutions:
  name: clouddrip
  ip: clouddrip-28b1e8.local
  filename: cloud_dripper/esp_cloud_dripper_2.yaml
  #ip: 192.168.8.179 #192.168.8.178

packages:
  pinout: !include _pinout.yaml
  humidity_sensor1: !include
    file: _humidity_sensor.yaml
    vars:
      id: 1
      pin: ${gpio_sense_1}
  humidity_sensor2: !include
    file: _humidity_sensor.yaml
    vars:
      id: 2
      pin: ${gpio_sense_2}
  humidity_sensor3: !include
    file: _humidity_sensor.yaml
    vars:
      id: 3
      pin: ${gpio_sense_3}
  leds: !include _leds.yaml
  sprinklers: !include _sprinklers.yaml
  system: !include _system_base.yaml
  pumps: !include _pumps_switches.yaml
  additiona_sensors: !include _additional_sensors.yaml
  settings: !include _configurable_settings.yaml
